name: Update fork
on:
  schedule:
    - cron:  '1 * * * *'
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: GoogleCloudPlatform/spark-on-k8s-operator
      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
          git fetch upstream relativity-master:upstream-master
          git reset --hard upstream-master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          branch: upstream-changes